# Generated by Django 2.2.4 on 2019-09-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('postcode', models.CharField(max_length=15)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['postcode', 'name'], name='stores_stor_postcod_7596e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('name', 'postcode')},
        ),
    ]
